# Generated by Django 5.0.4 on 2024-05-01 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')])),
                ('alpha3', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters are allowed.')])),
                ('number3', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
                ('name', models.CharField(max_length=100)),
                ('currencies', models.JSONField()),
                ('deleted_date', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
