# Generated by Django 5.0.4 on 2024-05-01 11:42

from django.db import migrations

def populate_currencies(apps, schema_editor):
    Currency = apps.get_model('countries', 'Currency')

    raw_data = [
        { 'name': 'pound sterling', 'alpha3': 'gbp', 'numeric3': '826', 'scale': 2 },
        { 'name': 'south africa rand', 'alpha3': 'zar', 'numeric3': '710', 'scale': 2 },
        { 'name': 'swazi ilanga', 'alpha3': 'szl', 'numeric3': '748', 'scale': 2 },
        { 'name': 'mozambique metical', 'alpha3': 'mzn', 'numeric3': '943', 'scale': 2 },
        { 'name': 'zimbabwe dollar', 'alpha3': 'zwl', 'numeric3': '932', 'scale': 2 },
        { 'name': 'us dollar', 'alpha3': 'usd', 'numeric3': '840', 'scale': 2 },
    ]

    for raw in raw_data:
        currency = Currency(
            alpha3=raw['alpha3'],
            name=raw['name'],
            numeric3=raw['numeric3'],
            scale=raw['scale'],
        )
        currency.save()

def undo(apps, schema_editor):

    Currency = apps.get_model('countries', 'Currency')
    Currency.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_currencies, undo),
    ]
