#! /usr/bin/env bash

# curl \
#     -H  'Accept: application/json; indent=4' \
#     http://localhost:8000/countries/

# echo

curl \
    -H  'Accept: application/json; indent=4' \
    http://localhost:8000/countries/?currency=gbp

echo