#! /usr/bin/env bash

echo "get all countries"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/
echo

echo "get country by alpha2"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/za/
echo

echo "get country by alpha3"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/moz/
echo

echo "get countries with currency"

echo "currency=gbp"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/?currency=gbp
echo

echo "currency=zar"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/?currency=zar
echo

echo "delete country for id = 1"
curl -X "DELETE" -H  'Accept: application/json; indent=4' http://localhost:8000/countries/1/
echo

echo "get country by id = 1"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/1/
echo
