#! /usr/bin/env bash

echo "get all countries"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/
echo

echo "get countries with currency"

echo "currency=gbp"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/?currency=gbp
echo

echo "currency=zar"
curl -H  'Accept: application/json; indent=4' http://localhost:8000/countries/?currency=zar
echo